
services:
  node-project:
    container_name: e-commerce-app
    image: alethrome/e-commerce-app
    build: .
    ports: 
      - "5000:5000"
    environment:
      - PG_DB=e-commerce
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_HOST=e-commerce-db
    depends_on:
      - node-db
    restart: always
    volumes: 
      - .:/app

  node-db:
    container_name: e-commerce-db
    image: postgres:12
    ports:
      - "8080:5432"
    environment:
      - POSTGRES_DB=e-commerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  migrate:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      npm install &&
      npx sequelize-cli db:migrate --migrations-path src/migrations --config src/config/config.json --models-path src/models"
    environment:
      - PG_DB=e-commerce
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_HOST=e-commerce-db
    depends_on:
      - node-db
      


